// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiaNjtURIq_LXDT_YrOU_D-MIcfa5GQOQ',
    appId: '1:794936802588:web:0558c9526fae16104f4ed9',
    messagingSenderId: '794936802588',
    projectId: 'waveapp-57e3d',
    authDomain: 'waveapp-57e3d.firebaseapp.com',
    storageBucket: 'waveapp-57e3d.firebasestorage.app',
    measurementId: 'G-T4JW00NMJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkEYpN2LdpQ98mAqKyC4X23kGaSZet9iY',
    appId: '1:794936802588:android:e2da1164c7b8f1744f4ed9',
    messagingSenderId: '794936802588',
    projectId: 'waveapp-57e3d',
    storageBucket: 'waveapp-57e3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvIw1x3HEA7wP_JMieTAS13JuZlLEHfGM',
    appId: '1:794936802588:ios:15634377de0138724f4ed9',
    messagingSenderId: '794936802588',
    projectId: 'waveapp-57e3d',
    storageBucket: 'waveapp-57e3d.firebasestorage.app',
    iosBundleId: 'com.codev13.getxWaveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvIw1x3HEA7wP_JMieTAS13JuZlLEHfGM',
    appId: '1:794936802588:ios:15634377de0138724f4ed9',
    messagingSenderId: '794936802588',
    projectId: 'waveapp-57e3d',
    storageBucket: 'waveapp-57e3d.firebasestorage.app',
    iosBundleId: 'com.codev13.getxWaveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiaNjtURIq_LXDT_YrOU_D-MIcfa5GQOQ',
    appId: '1:794936802588:web:9db9c676932f41754f4ed9',
    messagingSenderId: '794936802588',
    projectId: 'waveapp-57e3d',
    authDomain: 'waveapp-57e3d.firebaseapp.com',
    storageBucket: 'waveapp-57e3d.firebasestorage.app',
    measurementId: 'G-7TG6MGYWHN',
  );
}
